# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_auto_20170601_2212'),
    ]

    operations = [
        migrations.RenameField('Reading', 'humidity', 'humidity_new'),
    ]
