# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_auto_20170601_2217'),
    ]

    operations = [
        migrations.RenameField('Reading', 'humidity_new', 'humidity'),
    ]
